# Generated by Django 4.2.3 on 2023-07-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_end_time_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.listing'),
        ),
    ]
